export interface CitizenForm {
    image: string,
    firstname: string,
    lastname: string,
    gender: string,
    email: string,
    social_security_number: string,
    birthday: string,
    phone: string,
    departments: string[],
    street: string,
    region_uuid: string,
    municipality_uuid: string,
    city_uuid: string,
    post_code: string,
    origin: string,
    diagnoses: string[],
    addictions: string[],
    date_admitted: string,
    date_discharged: string,
    note: string,
    has_system_access: boolean,
    has_chat_access: boolean,
    has_duty_schedule_access: boolean,
    has_bullet_board_access: boolean,
}